baseURL: https://yuxincheng.netlify.app/
languageCode: en-us
title: Portfolio website for Yuxin
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: READY FOR THE JOURNEY?
    subtitle: |-
      DISCOVER MY FOOTPRINT AND DATA PROJECTS
    title: Welcome to Yuxin Cheng's blog
  blog: {}
  contact:
    address:
      - city: 
        country: 
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: noreply@plsusemessagefunctionthx.com
        title: Email
    enable: yes
    phone:
      - phone: (000) 666-0000 8888
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Y.Cheng Ltd
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/londonbschool/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/yuxin-cheng
  image: ''
  name: Your name
  navigation:
    button1:
      - name: READY FOR THE JOURNEY?
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: About me
        url: aboutme
    menu: Menu
    subtitle: Y.Cheng
    title: BLOG
  tiles:
    enable: yes
    showcase:
      - image: UK1.jpg
        subtitle: London - where I base this year and hopefully also in next two years
        title: United Kingdom
        url: blogs/london
      - image: DE1.jpg
        subtitle: Frankfurt - where I spent five years of youth
        title: Germany
        url: blogs/frankfurt
      - image: FR1.jpg
        subtitle: Paris - my favorite city in Europe, but only for vacation pls
        title: France
        url: blogs/paris
      - image: IT1.jpg
        subtitle: Milan - almost forgot I have lived here for half a year but love this city absolutely
        title: Italy
        url: blogs/milan
      - image: SP1.jpg
        subtitle: Barcelona - tip to escape the cold winter in central Europe
        title: Spain
        url: blogs/barcelona
      - image: Data.jpg
        subtitle: Click here to find out one of the data projects I have done
        title: Data Project
        url: blogs/data
  two:
    buttonText: CLICK HERE
    enable: yes
    subtitle: "Having lived in Europe for eight years as a foreigner, I wrote this Blog to share my own experiences 
    in traveling around Europe. Besides traveling, I love coding and am thrilled to share one of the projects I have done with you.
    Thank you for visiting the site and I look forward to receiving your messages!"
    title: Welcome
    url: blogs
    
